name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # - name: Set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8

    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew

    # - name: Build with Gradle
    #   run: ./gradlew build
      
    - name: Docker image build
      run: docker build -t docker.io/spryamni/demo-app:java-image .

    - name: Docker Login
      run: docker login -u "${{secrets.DOCKER_USERNAME}}"-p "${{secrets.DOCKER_PASSWORD}}"

    - name: Push image to Dockerhub
      run: docker push docker.io/spryamni/demo-app:java-image
